name: 'Terraform Validation'

on:
  pull_request:
    paths:
      - 'environments/**/*.tf'
      - 'modules/**/*.tf'
      - '.github/workflows/terraform-validation.yml'
  push:
    branches: [main]
    paths:
      - 'environments/**/*.tf'
      - 'modules/**/*.tf'

env:
  TF_VERSION: '1.6.0'

jobs:
  validate:
    name: 'Terraform Validate'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [production, staging]

    defaults:
      run:
        working-directory: environments/${{ matrix.environment }}/terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

  security:
    name: 'Security Scan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: true
          format: sarif
          additional_args: --exclude-downloaded-modules

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          soft_fail: true
          output_format: sarif
          download_external_modules: false

  lint:
    name: 'Terraform Lint'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint (modules)
        run: |
          for module in modules/*/; do
            echo "Linting $module"
            tflint --chdir=$module
          done

      - name: Run TFLint (environments)
        run: |
          for env in environments/*/terraform/; do
            echo "Linting $env"
            tflint --chdir=$env
          done
